/**
 * GujRaksha (ગુજ રક્ષા) — Database Initial Seed Definitions
 * Copyright (c) 2026 Fenil Patel. All Rights Reserved.
 *
 * Direct database seeding models (No JSON files required).
 */

export const initialDepartments = [
  {
    "code": "HOME",
    "name": "Home Department / Gujarat Police",
    "category": "Law & Order & Crime Detection",
    "nodal_officer": "DGP / DIG State Command & Control Center",
    "contact_email": "police.surveillance@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0000",
    "status": "ACTIVE",
    "icon": "Shield",
    "color": "#f87171",
    "description": "Statewide police public surveillance, traffic management, city junctions, border checkpoints, and eGujCop integration.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "TRANSPORT",
    "name": "Transport Department / RTO Gujarat",
    "category": "Mobility & Checkposts",
    "nodal_officer": "Transport Commissioner / RTO Surveillance Head",
    "contact_email": "rto.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1361",
    "status": "ACTIVE",
    "icon": "Truck",
    "color": "#38bdf8",
    "description": "RTO automated driving testing tracks, border checkposts, weighbridges, and VAHAN/SARTHI integration nodes.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "CIVIL_SUPPLIES",
    "name": "Food, Civil Supplies & Consumer Affairs",
    "category": "PDS & Supply Chain",
    "nodal_officer": "Director of Civil Supplies / Storage Division",
    "contact_email": "civilsupplies.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1066",
    "status": "ACTIVE",
    "icon": "Wheat",
    "color": "#fbbf24",
    "description": "State food grain godowns, Fair Price PDS distribution shops, and civil supply logistics warehouses.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "PORTS",
    "name": "Gujarat Maritime Board & Ports",
    "category": "Maritime & Coastal Security",
    "nodal_officer": "Chief Port Officer / Maritime Security",
    "contact_email": "gmb.surveillance@gujarat.gov.in",
    "contact_phone": "+91 79 2323 8346",
    "status": "ACTIVE",
    "icon": "Anchor",
    "color": "#22d3ee",
    "description": "Non-major port berths, coastal monitoring towers, cargo terminals, and maritime landing facilities.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "URBAN_DEV",
    "name": "Urban Development & Municipal Corporations",
    "category": "Smart Cities & Civic Infrastructure",
    "nodal_officer": "Chief Urban Planner / ICCC Operations Head",
    "contact_email": "urbandev.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0901",
    "status": "ACTIVE",
    "icon": "Building2",
    "color": "#818cf8",
    "description": "Ahmedabad (AMC), Surat (SMC), Vadodara (VMC), Rajkot (RMC) smart city ICCC networks and public plazas.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "ROADS_BUILDINGS",
    "name": "Roads & Buildings Department (R&B)",
    "category": "Highways & Public Infrastructure",
    "nodal_officer": "Chief Engineer (State Highways & Bridges)",
    "contact_email": "rnb.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1801",
    "status": "ACTIVE",
    "icon": "Route",
    "color": "#f97316",
    "description": "State highways, major flyovers, expressway toll plazas, river bridges, and key administrative secretariats.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "FOREST",
    "name": "Forests & Environment Department",
    "category": "Wildlife & Ecological Protection",
    "nodal_officer": "Principal Chief Conservator of Forests (Wildlife)",
    "contact_email": "forest.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 4125",
    "status": "ACTIVE",
    "icon": "Trees",
    "color": "#34d399",
    "description": "Gir Asiatic Lion Sanctuary, Blackbuck National Park, marine sanctuaries, and eco-sensitive checkposts.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "HEALTH",
    "name": "Health & Family Welfare Department",
    "category": "Healthcare & Civil Hospitals",
    "nodal_officer": "Additional Director (Medical Infrastructure)",
    "contact_email": "health.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0801",
    "status": "ACTIVE",
    "icon": "HeartPulse",
    "color": "#ec4899",
    "description": "Civil hospitals, medical college campuses, emergency trauma wards, and medical supply chain warehouses.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "EDUCATION",
    "name": "Education Department (GSEB / Colleges)",
    "category": "Academic & Examination Centers",
    "nodal_officer": "Director of Higher Education / Examination Controller",
    "contact_email": "education.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1301",
    "status": "ACTIVE",
    "icon": "GraduationCap",
    "color": "#a855f7",
    "description": "State board examination centers, university campuses, government colleges, and evaluation hubs.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "REVENUE",
    "name": "Revenue Department",
    "category": "Land Records & Collectorates",
    "nodal_officer": "Revenue Inspection Commissioner",
    "contact_email": "revenue.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1501",
    "status": "ACTIVE",
    "icon": "Landmark",
    "color": "#eab308",
    "description": "District Collectorates, Prant offices, Sub-Registrar registry hubs, and land record archival centers.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "ENERGY",
    "name": "Energy & Petrochemicals Department",
    "category": "Power & Critical Infrastructure",
    "nodal_officer": "Chief Electrical Inspector / Grid Security",
    "contact_email": "energy.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0701",
    "status": "ACTIVE",
    "icon": "Zap",
    "color": "#e11d48",
    "description": "GETCO 400kV high-voltage power substations, Charanka solar park, power generation plants, and gas grid hubs.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "INDUSTRIES",
    "name": "Industries & Mines (GIDC)",
    "category": "Industrial Corridors & Mining",
    "nodal_officer": "Managing Director (GIDC Infrastructure)",
    "contact_email": "gidc.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 2501",
    "status": "ACTIVE",
    "icon": "Factory",
    "color": "#64748b",
    "description": "GIDC industrial estates (Dahej, Sanand, Ankleshwar), mining royalty checkpoints, and chemical zones.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "WATER_RESOURCES",
    "name": "Water Resources & Narmada Water Supply",
    "category": "Dams, Reservoirs & Canals",
    "nodal_officer": "Chief Engineer (Narmada Project Surveillance)",
    "contact_email": "water.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 1601",
    "status": "ACTIVE",
    "icon": "Droplets",
    "color": "#06b6d4",
    "description": "Sardar Sarovar Dam, main Narmada canal network, water treatment plants, and major reservoir barrage sites.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "TOURISM",
    "name": "Tourism & Pilgrimage Development",
    "category": "Heritage & Public Attractions",
    "nodal_officer": "Director of Tourism Infrastructure",
    "contact_email": "tourism.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2322 2517",
    "status": "ACTIVE",
    "icon": "Compass",
    "color": "#10b981",
    "description": "Statue of Unity complex, Somnath temple corridor, Dwarka pilgrimage perimeter, Rann of Kutch tent city.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "GSDMA",
    "name": "Gujarat State Disaster Management Authority",
    "category": "Emergency & Disaster Response",
    "nodal_officer": "Emergency Operations Center Director",
    "contact_email": "gsdma.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 9220",
    "status": "ACTIVE",
    "icon": "LifeBuoy",
    "color": "#ef4444",
    "description": "State Emergency Operation Center (SEOC), coastal early warning cyclone towers, and flood monitoring outposts.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "AGRICULTURE",
    "name": "Agriculture & Farmers Welfare (APMC)",
    "category": "Agricultural Markets & Logistics",
    "nodal_officer": "Director of Agricultural Marketing",
    "contact_email": "agri.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 6000",
    "status": "ACTIVE",
    "icon": "Sprout",
    "color": "#84cc16",
    "description": "APMC market yards (Unjha, Gondal, Rajkot), seed certification centers, and cold storage facilities.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "PANCHAYAT",
    "name": "Panchayats & Rural Development",
    "category": "Rural Civic Centers",
    "nodal_officer": "Development Commissioner (Rural Surveillance)",
    "contact_email": "panchayat.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 3300",
    "status": "ACTIVE",
    "icon": "Home",
    "color": "#14b8a6",
    "description": "Taluka Panchayat seva sadans, eGram connectivity centers, and rural infrastructure projects.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "LABOUR",
    "name": "Labour, Skill Development & Employment",
    "category": "Industrial Training & Employment",
    "nodal_officer": "Director of Employment & Training (DET)",
    "contact_email": "labour.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 3900",
    "status": "ACTIVE",
    "icon": "Wrench",
    "color": "#6366f1",
    "description": "Government ITI workshops, mega skill training complexes, and labor welfare commissionerates.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "SOCIAL_JUSTICE",
    "name": "Social Justice & Empowerment",
    "category": "Welfare & Residential Centers",
    "nodal_officer": "Director of Social Defense",
    "contact_email": "socialjustice.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 3200",
    "status": "ACTIVE",
    "icon": "Users",
    "color": "#d946ef",
    "description": "Samras student hostels, senior citizen care centers, and special rehabilitation homes.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "WOMEN_CHILD",
    "name": "Women & Child Development",
    "category": "Protection & Shelter Centers",
    "nodal_officer": "Commissioner of Women and Child Welfare",
    "contact_email": "wcd.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 7900",
    "status": "ACTIVE",
    "icon": "Heart",
    "color": "#f43f5e",
    "description": "Nari Sanrakshan Gruh shelter homes, smart Anganwadi model hubs, and child care institutions.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "SPORTS_YOUTH",
    "name": "Sports, Youth & Cultural Activities",
    "category": "Stadiums & Cultural Arenas",
    "nodal_officer": "Director General (Sports Authority of Gujarat)",
    "contact_email": "sports.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 8000",
    "status": "ACTIVE",
    "icon": "Trophy",
    "color": "#f59e0b",
    "description": "State sports complexes, athletics academies, swimming complexes, and cultural auditoriums.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "SCIENCE_TECH",
    "name": "Science & Technology (GIL / Science City)",
    "category": "Innovation & Data Centers",
    "nodal_officer": "Managing Director (Gujarat Informatics Ltd)",
    "contact_email": "dst.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0301",
    "status": "ACTIVE",
    "icon": "Cpu",
    "color": "#0284c7",
    "description": "Gujarat Science City pavilions, State Data Center (SDC), and regional science centers.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "FINANCE",
    "name": "Finance & State Tax Department (GST)",
    "category": "Taxation & Border Commercial Posts",
    "nodal_officer": "Chief Commissioner of State Tax",
    "contact_email": "finance.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0501",
    "status": "ACTIVE",
    "icon": "BadgePercent",
    "color": "#16a34a",
    "description": "State GST surveillance squads, mobile tax enforcement corridors, and treasury vaults.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "GENERAL_ADMIN",
    "name": "General Administration Department (GAD)",
    "category": "Secretariat Security",
    "nodal_officer": "Chief Security Officer (Sachivalaya Complex)",
    "contact_email": "gad.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 0300",
    "status": "ACTIVE",
    "icon": "ShieldCheck",
    "color": "#475569",
    "description": "New Sachivalaya, Swarnim Sankul 1 & 2, Vidhan Sabha complex, and Raj Bhavan perimeter.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "LEGAL",
    "name": "Legal Department & Judiciary",
    "category": "Judicial Complexes & Courts",
    "nodal_officer": "Registrar (Infrastructure - High Court of Gujarat)",
    "contact_email": "legal.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 2100",
    "status": "ACTIVE",
    "icon": "Scale",
    "color": "#7c3aed",
    "description": "High Court of Gujarat perimeter, District & Sessions courts, and judicial training academies.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "TRIBAL_DEV",
    "name": "Tribal Development Department",
    "category": "Tribal Welfare Infrastructure",
    "nodal_officer": "Commissioner of Tribal Development",
    "contact_email": "tribal.cctv@gujarat.gov.in",
    "contact_phone": "+91 79 2325 3600",
    "status": "ACTIVE",
    "icon": "Mountain",
    "color": "#0d9488",
    "description": "Eklavya Model Residential Schools, tribal area training centers, and border tribal checkposts.",
    "created_at": "2026-08-20T10:00:00.000Z"
  },
  {
    "code": "PRIVATE_FEED",
    "name": "Private Commercial & Society Feeder",
    "category": "Public-Facing Commercial & Societies",
    "nodal_officer": "Gujarat Police Public-Private CCTV Integration Cell",
    "contact_email": "private.cctv@sentinelgujarat.in",
    "contact_phone": "+91 79 2325 9999",
    "status": "ACTIVE",
    "icon": "Store",
    "color": "#8b5cf6",
    "description": "Public-facing CCTV cameras installed by residential societies, malls, jewelry associations, and commercial establishments.",
    "created_at": "2026-08-20T10:00:00.000Z"
  }
];

export const initialCameras = [
  {
    "id": "gov-feed-31",
    "camera_code": "gj-gov-32",
    "name": "orion camera",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "ahmedabd",
    "taluka": "",
    "latitude": 23,
    "longitude": 72,
    "address": "",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Live Sentinel Feeder (H264/MP4)",
    "stream_url": "rtsp://admin:Admin@123@192.168.1.223:554/sub",
    "retention_days": 15,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T12:41:50.339Z",
    "updated_at": "2026-08-26T08:29:17.918Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://admin:Admin@123@192.168.1.223:554/sub",
      "whep": "http://localhost:8889/stream/31/whep",
      "hls": "http://localhost:8888/stream/31/index.m3u8"
    },
    "rtsp_url": "rtsp://admin:Admin@123@192.168.1.223:554/sub",
    "whep_url": "http://localhost:8889/stream/31/whep",
    "hls_url": "http://localhost:8888/stream/31/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 30,
      "codec": "H.264",
      "bitrate": "4Mbps"
    },
    "detection_mode": "ANPR_DETECTION"
  },
  {
    "id": "gov-feed-1",
    "camera_code": "GJ-GOV-001",
    "name": "Camera 1 (01 Chiman bhai Bridge)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.051570826744054,
    "longitude": 72.56066561780197,
    "address": "01 Chiman bhai Bridge",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/1",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.447Z",
    "updated_at": "2026-08-26T08:28:11.210Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/1",
      "whep": "http://live.corp8.cloud:8889/stream/1/whep",
      "hls": "https://live.corp8.cloud/live/stream/1/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/1",
    "whep_url": "http://live.corp8.cloud:8889/stream/1/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/1/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-2",
    "camera_code": "GJ-GOV-002",
    "name": "Camera 2 (02 Janpath)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 22.986093125785636,
    "longitude": 72.54072157796065,
    "address": "02 Janpath",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/2",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.447Z",
    "updated_at": "2026-08-25T13:48:36.447Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/2",
      "whep": "http://live.corp8.cloud:8889/stream/2/whep",
      "hls": "https://live.corp8.cloud/live/stream/2/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/2",
    "whep_url": "http://live.corp8.cloud:8889/stream/2/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/2/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-3",
    "camera_code": "GJ-GOV-003",
    "name": "Camera 3 (03 O.N.G.C. Office)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 22.990058270041622,
    "longitude": 72.57338006166808,
    "address": "03 O.N.G.C. Office",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/3",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.454Z",
    "updated_at": "2026-08-25T13:48:36.454Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/3",
      "whep": "http://live.corp8.cloud:8889/stream/3/whep",
      "hls": "https://live.corp8.cloud/live/stream/3/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/3",
    "whep_url": "http://live.corp8.cloud:8889/stream/3/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/3/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-4",
    "camera_code": "GJ-GOV-004",
    "name": "Camera 4 (04 Paldi Circle)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.039884664187035,
    "longitude": 72.57031254713564,
    "address": "04 Paldi Circle",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/4",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.454Z",
    "updated_at": "2026-08-25T13:48:36.454Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/4",
      "whep": "http://live.corp8.cloud:8889/stream/4/whep",
      "hls": "https://live.corp8.cloud/live/stream/4/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/4",
    "whep_url": "http://live.corp8.cloud:8889/stream/4/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/4/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-5",
    "camera_code": "GJ-GOV-005",
    "name": "Camera 5 (05 Visat teen Rasta)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.04401885092156,
    "longitude": 72.54291516543708,
    "address": "05 Visat teen Rasta",
    "ownership_type": "GOVERNMENT",
    "camera_type": "FIXED_BULLET",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/5",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.454Z",
    "updated_at": "2026-08-25T13:48:36.454Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/5",
      "whep": "http://live.corp8.cloud:8889/stream/5/whep",
      "hls": "https://live.corp8.cloud/live/stream/5/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/5",
    "whep_url": "http://live.corp8.cloud:8889/stream/5/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/5/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-6",
    "camera_code": "GJ-GOV-006",
    "name": "Camera 6 (06 Timbavadi gate-Junagadh)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Junagadh",
    "taluka": "Junagadh",
    "latitude": 21.51107362900693,
    "longitude": 70.44294814719935,
    "address": "06 Timbavadi gate-Junagadh",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/6",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.455Z",
    "updated_at": "2026-08-25T13:48:36.455Z",
    "codec": "HEVC",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/6",
      "whep": "http://live.corp8.cloud:8889/stream/6/whep",
      "hls": "https://live.corp8.cloud/live/stream/6/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/6",
    "whep_url": "http://live.corp8.cloud:8889/stream/6/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/6/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "HEVC",
      "bitrate": "1923Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-7",
    "camera_code": "GJ-GOV-007",
    "name": "Camera 7 (07 hero-showroom-gir-somnath)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Gir Somnath",
    "taluka": "Gir Somnath",
    "latitude": 20.890466053095782,
    "longitude": 70.3576285294143,
    "address": "07 hero-showroom-gir-somnath",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/7",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.455Z",
    "updated_at": "2026-08-25T13:48:36.455Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/7",
      "whep": "http://live.corp8.cloud:8889/stream/7/whep",
      "hls": "https://live.corp8.cloud/live/stream/7/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/7",
    "whep_url": "http://live.corp8.cloud:8889/stream/7/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/7/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-8",
    "camera_code": "GJ-GOV-008",
    "name": "Camera 8 (08 majewadi-gate-junagadh)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Junagadh",
    "taluka": "Junagadh",
    "latitude": 21.50383570516219,
    "longitude": 70.46669966093336,
    "address": "08 majewadi-gate-junagadh",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/8",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.456Z",
    "updated_at": "2026-08-25T13:48:36.456Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/8",
      "whep": "http://live.corp8.cloud:8889/stream/8/whep",
      "hls": "https://live.corp8.cloud/live/stream/8/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/8",
    "whep_url": "http://live.corp8.cloud:8889/stream/8/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/8/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-9",
    "camera_code": "GJ-GOV-009",
    "name": "Camera 9 (09 new-bypass-near-by-circle-junagadh-2)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Junagadh",
    "taluka": "Junagadh",
    "latitude": 21.529756434435757,
    "longitude": 70.43938787078913,
    "address": "09 new-bypass-near-by-circle-junagadh-2",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/9",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.456Z",
    "updated_at": "2026-08-25T13:48:36.456Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/9",
      "whep": "http://live.corp8.cloud:8889/stream/9/whep",
      "hls": "https://live.corp8.cloud/live/stream/9/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/9",
    "whep_url": "http://live.corp8.cloud:8889/stream/9/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/9/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-10",
    "camera_code": "GJ-GOV-010",
    "name": "Camera 10 (10 char-chowk-road-2-junagadh)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Junagadh",
    "taluka": "Junagadh",
    "latitude": 21.521025296682772,
    "longitude": 70.47731773181665,
    "address": "10 char-chowk-road-2-junagadh",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/10",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.457Z",
    "updated_at": "2026-08-25T13:48:36.457Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/10",
      "whep": "http://live.corp8.cloud:8889/stream/10/whep",
      "hls": "https://live.corp8.cloud/live/stream/10/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/10",
    "whep_url": "http://live.corp8.cloud:8889/stream/10/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/10/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-11",
    "camera_code": "GJ-GOV-011",
    "name": "Camera 11 (11 dolatpara-junagadh)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Junagadh",
    "taluka": "Junagadh",
    "latitude": 21.536160697010764,
    "longitude": 70.45314707447295,
    "address": "11 dolatpara-junagadh",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/11",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.457Z",
    "updated_at": "2026-08-25T13:48:36.457Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/11",
      "whep": "http://live.corp8.cloud:8889/stream/11/whep",
      "hls": "https://live.corp8.cloud/live/stream/11/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/11",
    "whep_url": "http://live.corp8.cloud:8889/stream/11/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/11/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-12",
    "camera_code": "GJ-GOV-012",
    "name": "Camera 12 (12 Tri Mandir Adalaj Tollnaka)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Gandhinagar",
    "taluka": "Gandhinagar",
    "latitude": 23.21717999453755,
    "longitude": 72.65995375114436,
    "address": "12 Tri Mandir Adalaj Tollnaka",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/12",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.457Z",
    "updated_at": "2026-08-25T13:48:36.457Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/12",
      "whep": "http://live.corp8.cloud:8889/stream/12/whep",
      "hls": "https://live.corp8.cloud/live/stream/12/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/12",
    "whep_url": "http://live.corp8.cloud:8889/stream/12/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/12/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-13",
    "camera_code": "GJ-GOV-013",
    "name": "Camera 13 (13 CN Vidhyalaya)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.025180711018205,
    "longitude": 72.56158832245181,
    "address": "13 CN Vidhyalaya",
    "ownership_type": "GOVERNMENT",
    "camera_type": "FIXED_BULLET",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/13",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.458Z",
    "updated_at": "2026-08-25T13:48:36.458Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/13",
      "whep": "http://live.corp8.cloud:8889/stream/13/whep",
      "hls": "https://live.corp8.cloud/live/stream/13/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/13",
    "whep_url": "http://live.corp8.cloud:8889/stream/13/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/13/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 12.5,
      "codec": "H264",
      "bitrate": "902Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-14",
    "camera_code": "GJ-GOV-014",
    "name": "Camera 14 (14 Delight)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.041310733119023,
    "longitude": 72.57533215478381,
    "address": "14 Delight",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/14",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.458Z",
    "updated_at": "2026-08-25T13:48:36.458Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/14",
      "whep": "http://live.corp8.cloud:8889/stream/14/whep",
      "hls": "https://live.corp8.cloud/live/stream/14/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/14",
    "whep_url": "http://live.corp8.cloud:8889/stream/14/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/14/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 12.5,
      "codec": "H264",
      "bitrate": "980Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-15",
    "camera_code": "GJ-GOV-015",
    "name": "Camera 15 (15 Suvidha park)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 22.993210993516634,
    "longitude": 72.60867466916963,
    "address": "15 Suvidha park",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/15",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.458Z",
    "updated_at": "2026-08-25T13:48:36.458Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/15",
      "whep": "http://live.corp8.cloud:8889/stream/15/whep",
      "hls": "https://live.corp8.cloud/live/stream/15/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/15",
    "whep_url": "http://live.corp8.cloud:8889/stream/15/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/15/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 12.5,
      "codec": "H264",
      "bitrate": "690Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-16",
    "camera_code": "GJ-GOV-016",
    "name": "Camera 16 (16 Visat P2)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.042186817377516,
    "longitude": 72.54770036821843,
    "address": "16 Visat P2",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/16",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.458Z",
    "updated_at": "2026-08-25T13:48:36.458Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/16",
      "whep": "http://live.corp8.cloud:8889/stream/16/whep",
      "hls": "https://live.corp8.cloud/live/stream/16/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/16",
    "whep_url": "http://live.corp8.cloud:8889/stream/16/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/16/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 12.5,
      "codec": "H264",
      "bitrate": "961Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-17",
    "camera_code": "GJ-GOV-017",
    "name": "Camera 17 (17 Rajkot Bus Port CCTV)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Rajkot",
    "taluka": "Rajkot",
    "latitude": 22.287321142682437,
    "longitude": 70.79422557767238,
    "address": "17 Rajkot Bus Port CCTV",
    "ownership_type": "GOVERNMENT",
    "camera_type": "FIXED_BULLET",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/17",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.459Z",
    "updated_at": "2026-08-25T13:48:36.459Z",
    "codec": "HEVC",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/17",
      "whep": "http://live.corp8.cloud:8889/stream/17/whep",
      "hls": "https://live.corp8.cloud/live/stream/17/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/17",
    "whep_url": "http://live.corp8.cloud:8889/stream/17/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/17/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 24.98,
      "codec": "HEVC",
      "bitrate": "671Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-18",
    "camera_code": "GJ-GOV-018",
    "name": "Camera 18 (18 Rajkot CCTV)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Rajkot",
    "taluka": "Rajkot",
    "latitude": 22.31153165432524,
    "longitude": 70.7968457273067,
    "address": "18 Rajkot CCTV",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/18",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.459Z",
    "updated_at": "2026-08-25T13:48:36.459Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/18",
      "whep": "http://live.corp8.cloud:8889/stream/18/whep",
      "hls": "https://live.corp8.cloud/live/stream/18/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/18",
    "whep_url": "http://live.corp8.cloud:8889/stream/18/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/18/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-19",
    "camera_code": "GJ-GOV-019",
    "name": "Camera 19 (19 KHAPARIA GRAM PANCHAYAT , TALUKA GANDEVI, DISTRICT NAVSARI)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.832412490229324,
    "longitude": 72.99422291510123,
    "address": "19 KHAPARIA GRAM PANCHAYAT , TALUKA GANDEVI, DISTRICT NAVSARI",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/19",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.460Z",
    "updated_at": "2026-08-25T13:48:36.460Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/19",
      "whep": "http://live.corp8.cloud:8889/stream/19/whep",
      "hls": "https://live.corp8.cloud/live/stream/19/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/19",
    "whep_url": "http://live.corp8.cloud:8889/stream/19/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/19/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-20",
    "camera_code": "GJ-GOV-020",
    "name": "Camera 20 (20 Mohanpura)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Gandhinagar",
    "taluka": "Gandhinagar",
    "latitude": 23.214299385051042,
    "longitude": 72.63215288256731,
    "address": "20 Mohanpura",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/20",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.460Z",
    "updated_at": "2026-08-25T13:48:36.460Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/20",
      "whep": "http://live.corp8.cloud:8889/stream/20/whep",
      "hls": "https://live.corp8.cloud/live/stream/20/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/20",
    "whep_url": "http://live.corp8.cloud:8889/stream/20/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/20/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-21",
    "camera_code": "GJ-GOV-021",
    "name": "Camera 21 (23 Patan Dethali Char Rasta)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Patan",
    "taluka": "Patan",
    "latitude": 23.87238377265961,
    "longitude": 72.14265986458231,
    "address": "23 Patan Dethali Char Rasta",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/21",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.460Z",
    "updated_at": "2026-08-25T13:48:36.460Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/21",
      "whep": "http://live.corp8.cloud:8889/stream/21/whep",
      "hls": "https://live.corp8.cloud/live/stream/21/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/21",
    "whep_url": "http://live.corp8.cloud:8889/stream/21/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/21/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-22",
    "camera_code": "GJ-GOV-022",
    "name": "Camera 22 (28 BK Mervada tran Rasta)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Ahmedabad",
    "taluka": "Ahmedabad",
    "latitude": 23.040651786198662,
    "longitude": 72.53320623337027,
    "address": "28 BK Mervada tran Rasta",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/22",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.461Z",
    "updated_at": "2026-08-25T13:48:36.461Z",
    "codec": "HEVC",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/22",
      "whep": "http://live.corp8.cloud:8889/stream/22/whep",
      "hls": "https://live.corp8.cloud/live/stream/22/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/22",
    "whep_url": "http://live.corp8.cloud:8889/stream/22/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/22/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "HEVC",
      "bitrate": "2091Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-23",
    "camera_code": "GJ-GOV-023",
    "name": "Camera 23 (30 kheram)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Gandhinagar",
    "taluka": "Gandhinagar",
    "latitude": 23.203972938233747,
    "longitude": 72.63053400353465,
    "address": "30 kheram",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/23",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.461Z",
    "updated_at": "2026-08-25T13:48:36.461Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/23",
      "whep": "http://live.corp8.cloud:8889/stream/23/whep",
      "hls": "https://live.corp8.cloud/live/stream/23/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/23",
    "whep_url": "http://live.corp8.cloud:8889/stream/23/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/23/index.m3u8",
    "stream_properties": {
      "resolution": "1280x720",
      "fps": 25,
      "codec": "H264",
      "bitrate": "4001Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-24",
    "camera_code": "GJ-GOV-024",
    "name": "Camera 24 (33 dehgam)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Gandhinagar",
    "taluka": "Gandhinagar",
    "latitude": 23.202490166177398,
    "longitude": 72.63189964195556,
    "address": "33 dehgam",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/24",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.462Z",
    "updated_at": "2026-08-25T13:48:36.462Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/24",
      "whep": "http://live.corp8.cloud:8889/stream/24/whep",
      "hls": "https://live.corp8.cloud/live/stream/24/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/24",
    "whep_url": "http://live.corp8.cloud:8889/stream/24/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/24/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-25",
    "camera_code": "GJ-GOV-025",
    "name": "Camera 25 (34 dhanori)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.815833163736293,
    "longitude": 72.90019168518673,
    "address": "34 dhanori",
    "ownership_type": "GOVERNMENT",
    "camera_type": "FIXED_BULLET",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/25",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.462Z",
    "updated_at": "2026-08-25T13:48:36.462Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/25",
      "whep": "http://live.corp8.cloud:8889/stream/25/whep",
      "hls": "https://live.corp8.cloud/live/stream/25/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/25",
    "whep_url": "http://live.corp8.cloud:8889/stream/25/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/25/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-26",
    "camera_code": "GJ-GOV-026",
    "name": "Camera 26 (35 TANKAL)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.822437715509633,
    "longitude": 72.96629666763864,
    "address": "35 TANKAL",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/26",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.463Z",
    "updated_at": "2026-08-25T13:48:36.463Z",
    "codec": "HEVC",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/26",
      "whep": "http://live.corp8.cloud:8889/stream/26/whep",
      "hls": "https://live.corp8.cloud/live/stream/26/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/26",
    "whep_url": "http://live.corp8.cloud:8889/stream/26/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/26/index.m3u8",
    "stream_properties": {
      "resolution": "2560x1440",
      "fps": 13.35,
      "codec": "HEVC",
      "bitrate": "2411Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-27",
    "camera_code": "GJ-GOV-027",
    "name": "Camera 27 (36 bilimora)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.896850566899115,
    "longitude": 72.9462208408871,
    "address": "36 bilimora",
    "ownership_type": "GOVERNMENT",
    "camera_type": "DOME_INDOOR",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/27",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.463Z",
    "updated_at": "2026-08-25T13:48:36.463Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/27",
      "whep": "http://live.corp8.cloud:8889/stream/27/whep",
      "hls": "https://live.corp8.cloud/live/stream/27/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/27",
    "whep_url": "http://live.corp8.cloud:8889/stream/27/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/27/index.m3u8",
    "stream_properties": {
      "resolution": "1280x960",
      "fps": 24.86,
      "codec": "H264",
      "bitrate": "1112Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-28",
    "camera_code": "GJ-GOV-028",
    "name": "Camera 28 (37 bilimora)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.87694379413826,
    "longitude": 72.96361312942817,
    "address": "37 bilimora",
    "ownership_type": "GOVERNMENT",
    "camera_type": "ANPR_SPECIAL",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/28",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.464Z",
    "updated_at": "2026-08-25T13:48:36.464Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/28",
      "whep": "http://live.corp8.cloud:8889/stream/28/whep",
      "hls": "https://live.corp8.cloud/live/stream/28/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/28",
    "whep_url": "http://live.corp8.cloud:8889/stream/28/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/28/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-29",
    "camera_code": "GJ-GOV-029",
    "name": "Camera 29 (38 bilimora)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Navsari",
    "taluka": "Navsari",
    "latitude": 20.834222223690396,
    "longitude": 72.93138901764051,
    "address": "38 bilimora",
    "ownership_type": "GOVERNMENT",
    "camera_type": "FIXED_BULLET",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/29",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.465Z",
    "updated_at": "2026-08-25T13:48:36.465Z",
    "codec": "H264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/29",
      "whep": "http://live.corp8.cloud:8889/stream/29/whep",
      "hls": "https://live.corp8.cloud/live/stream/29/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/29",
    "whep_url": "http://live.corp8.cloud:8889/stream/29/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/29/index.m3u8",
    "stream_properties": {
      "resolution": "1280x960",
      "fps": 24.78,
      "codec": "H264",
      "bitrate": "907Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  },
  {
    "id": "gov-feed-30",
    "camera_code": "GJ-GOV-030",
    "name": "Camera 30 (Gandhidham Rambaugh p2)",
    "department_id": "HOME",
    "department_name": "Home Department / Gujarat Police",
    "district": "Kutch",
    "taluka": "Kutch",
    "latitude": 23.065506362440793,
    "longitude": 70.13301058154624,
    "address": "Gandhidham Rambaugh p2",
    "ownership_type": "GOVERNMENT",
    "camera_type": "PTZ",
    "vms_vendor": "Official Gujarat Police Sandbox Gateway",
    "stream_url": "rtsp://live.corp8.cloud:8554/stream/30",
    "retention_days": 30,
    "status": "ACTIVE",
    "installation_date": "2026-08-25",
    "created_at": "2026-08-25T13:48:36.465Z",
    "updated_at": "2026-08-25T13:48:36.465Z",
    "codec": "H.264",
    "urls": {
      "rtsp": "rtsp://live.corp8.cloud:8554/stream/30",
      "whep": "http://live.corp8.cloud:8889/stream/30/whep",
      "hls": "https://live.corp8.cloud/live/stream/30/index.m3u8"
    },
    "rtsp_url": "rtsp://live.corp8.cloud:8554/stream/30",
    "whep_url": "http://live.corp8.cloud:8889/stream/30/whep",
    "hls_url": "https://live.corp8.cloud/live/stream/30/index.m3u8",
    "stream_properties": {
      "resolution": "1920x1080",
      "fps": 25,
      "codec": "H.264",
      "bitrate": "2000Kbps"
    },
    "detection_mode": "TRAFFIC_MONITORING"
  }
];

export const initialWatchlist = [
  {
    "id": "wl-1787656966583",
    "vehicle_plate": "HR-98-AA-0000",
    "vehicle_type": "SUV / Sedan",
    "category": "STOLEN_VEHICLE",
    "fir_number": "t",
    "police_station": "State Police Surveillance Cell",
    "owner_name": "Under Investigation",
    "priority": "CRITICAL",
    "status": "ACTIVE",
    "description": "Flagged in statewide CCTV police watchlist.",
    "created_at": "2026-08-25T11:22:46.583Z"
  },
  {
    "id": "wl-1787647839738",
    "vehicle_plate": "GJ-01-HW-8888",
    "vehicle_type": "SUV / Scorpio",
    "category": "STOLEN_VEHICLE",
    "fir_number": "FIR #502/2026",
    "police_station": "SG Highway PS",
    "owner_name": "Under Investigation",
    "priority": "CRITICAL",
    "status": "ACTIVE",
    "description": "Flagged in statewide CCTV police watchlist.",
    "created_at": "2026-08-25T08:50:39.738Z"
  },
  {
    "id": "wl-1787303333857",
    "vehicle_plate": "GJ-01-AA-1234",
    "vehicle_type": "SUV / Sedan",
    "category": "STOLEN_VEHICLE",
    "fir_number": "FIR01",
    "police_station": "ahmedabad",
    "owner_name": "Under Investigation",
    "priority": "CRITICAL",
    "status": "ACTIVE",
    "description": "Flagged in statewide CCTV police watchlist.",
    "created_at": "2026-08-21T09:08:53.857Z"
  }
];

export const initialDetections = [];
